version: '3.8'

x-dev:
  &proxy_conf
  http_proxy: "${HTTP_PROXY}"
  https_proxy: "${HTTPS_PROXY}"

services:
  app:
    container_name: ${APP_NAME}
    image: node:14
    environment:
      CHOKIDAR_USEPOLLING: "true"
      # TS_NODE_FILES: "true" 
      TS_NODE_TRANSPILE_ONLY: "true"
      http_proxy: "${HTTP_PROXY}"
      https_proxy: "${HTTPS_PROXY}"
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    restart: always
    command: tail -f /dev/null