#!/bin/bash

# . "$(dirname "$0")/_/husky.sh"

set -e

echo "ENTER PRE-COMMIT"

# PROTECTED_BRANCH=("master" "dev")
PROTECTED_BRANCH=("fake")
BRANCH="$(git rev-parse --abbrev-ref HEAD)"

if [[ " ${PROTECTED_BRANCH[*]} " =~ " ${BRANCH} " ]]; then
# if [ "$branch" = "$PROTECTED_BRANCH" ]; then
  echo "You can't commit directly to protected branch "
  exit 1
fi